### ISSUE TITLE
Enhancement: stronger typing of `wallet_send`

### ISSUE THREAD

**Issue by crusso** [dfinity/cycles-wallet#50]
This is the current Candid for `wallet_send`
```
   wallet_send: (record { canister: principal; amount: nat64 }) -> ();
```
At the moment, it's just taking a principal, `p`, with no way of saying what interface that principal is expected  to support.
`wallet_rs.wallet_send` then blindly calls method `p.wallet_receive()` assuming it returns *some* result.

I think the wallet API could (perhaps) use a more strongly typed `wallet_send` method, something like the higher-order :

```
   wallet_send: (record { callback: () -> record { accepted : nat64 }; amount: nat64 }) -> ()
``` 
(excuse my Candid)

to make the contract clearer and safer. If we want to insist on the `wallet_receive` name, then the argument could be whole service with a single method instead.

```
  wallet_send: (record { canister: service { wallet_receive: () -> record { accepted : nat64 } }; amount: nat64 }) -> ()
```

Discovered debugging https://github.com/dfinity/examples/pull/71 (@lsgunnlsgunn `hello_cycles` example).

**Comment by adamspofford-dfinity** [comment]
Resolved in #130 - arbitrary canister functions are no longer called by the wallet_send function, which instead calls the management canister's deposit_cycles function.
