### ISSUE TITLE
Bug: Inconsistent (or too subtle) typing of wallet's `wallet_receive` and destination of wallet_send's `wallet_receive`

### ISSUE THREAD

**Issue by crusso** [dfinity/cycles-wallet#87]
Trying to extend Lisa's hello_cycles example, I noticed that the typing of

lib:did
```
Wallet.wallet_receive : () -> ()
```

and (the implicitly expected type) of the principal in `wallet_send`  are different:

```
wallet_receive : () -> variant { Ok : null; Err: Text};
```
Unless we are relying on funky properties of subtyping, that would mean that you can't send cycles to another wallet as the types don't match up.

Is that intentional or a bug?

Related to #50

**Comment by adamspofford-dfinity** [comment]
Resolved in #130 - arbitrary functions named wallet_receive are no longer called by the wallet.
