### ISSUE TITLE
cycles to SDR conversion is wrong 

### ISSUE THREAD

**Issue by ninegua** [dfinity/cycles-wallet#92]
As shown by this screenshot

![image](https://user-images.githubusercontent.com/1549364/120248205-0e0c4700-c22b-11eb-811b-f00442ec4d9b.png)

Also it may be better to replace $ with US$ if that was the intention, but that will require dynamically obtaining the rate of SDR to USD.

**Comment by wackyleo459** [comment]
The wallet now dynamically reflects accurate conversion rate from SDR to ICP.
Slider will show the cycles equivalent in ICP amount instead of USD.
https://github.com/dfinity/cycles-wallet/pull/123
