### ISSUE TITLE
Asset /authorize not found.

### ISSUE THREAD

**Issue by uney** [dfinity/cycles-wallet#99]
![Screen Shot 2021-06-11 at 7 08 38 PM](https://user-images.githubusercontent.com/2201149/121677444-7212f300-cae8-11eb-8a88-7a8e37b3f156.png)

**Comment by flyq** [comment]
Yes, I get the same error in Mac.

1. When I open http://localhost:8000/?canisterId=r7inp-6aaaa-aaaaa-aaabq-cai, it will auto to http://localhost:8000/authorize?canisterId=r7inp-6aaaa-aaaaa-aaabq-cai
![image](https://user-images.githubusercontent.com/16486808/122933319-204c5180-d3a1-11eb-8d49-baf69126f595.png)
2. fellow the command, and refresh it, it will be  Asset /authorize not found.

**Comment by adamspofford-dfinity** [comment]
Resolved in #132.
